name: Maven Central Package Release
on: [workflow_dispatch]

jobs:
  central-package-release-job:
    runs-on: ubuntu-latest
    name: Maven Central Package Release
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Java and Maven
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
      - name: Cache Local Maven Repository
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install GPG Secret Key
        env:
          GPG_SECRET_KEY: ${{ secrets.CENTRAL_GPG_SECRET_KEY }}
        run: |
          echo "$GPG_SECRET_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish Package to Maven Central
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.CENTRAL_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn --batch-mode --no-transfer-progress \
          deploy \
          -P release-central-package
