name: "OSSRH Package Release"
on: [workflow_dispatch]

jobs:
  ossrh-package-release-job:
    runs-on: ubuntu-latest
    name: OSSRH Package Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
      - name: Cache Local Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install GPG Secret Key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish Package to OSSRH
        run: |
          mvn --batch-mode --no-transfer-progress \
          deploy \
          -P release-ossrh-package \
          -D gpg.passphrase=$OSSRH_GPG_SECRET_KEY_PASSWORD
        env:
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
